export const projects = [
    {
        title: "Inventory Management System",
        subtitle: "Python + Connexion + MySQL + OpenAPI + Kafka",
        description: "Web-based Inventory Management System. Tracks inventory availability at all points of your supply chain. ",
        image: "./img/inventory.png",
        link: "https://github.com/QI-D/Inventory_Management_System",
        l1: "Microservices Architecture",
        l2: "Inventory Intake",
        l3: "Order Management",
        l4: "Revenue Report",
        l5: "Health Check",
    },{
        title: "Smart Roster Scheduler",
        subtitle: "Python + Flask + jQuery + MySQL",
        description: "In partnership with Subject Matter Expertise from BC Women's Hospital, to simplify the process for shift assigments.",
        image: "./img/scheduler.jpg",
        link: "https://github.com/QI-D/SMART-roster",
        l1: "User Authentication",
        l2: "Shift Assignments",
        l3: "Alert for Conflict and Restriction",
        l4: "Test-driven Development",
        l5: "Agile Methodology",
    },
    {
        title: "Social Reminder",
        subtitle: "NodeJS + ExpressJS + EJS + MongoDB",
        description: "Web-based Reminder App. Connect with your friends and see what they are up to.",
        image: "./img/reminder_app.jpg",
        link: "https://github.com/QI-D/Reminder-App-Project",
        l1: "MVC Architecture",
        l2: "User Authentication",
        l3: "Friend System",
        l4: "Reminder Creation & Modification",
        l5: "Agile Methodology",
    },
    {
        title: "Snake Game",
        subtitle: "Python + PyGame + Flask + MySQL",
        description: "Starving Snake! Get as many apples as you can, try to not eat yourself. What's your ranking on the leaderboard?",
        image: "./img/snake.jpg",
        link: "https://github.com/QI-D/SnakeGame",
        l1: "Difficult Levels",
        l2: "Speed based on level",
        l3: "Score per apple based on level",
        l4: "Store player and game info in database",
        l5: "Web-based Leaderboard",
    },
    {
        title: "Maze Game",
        subtitle: "Python + PyGame + Flask",
        description: "A hero will not get stopped by a maze! Gear up, collecte the treasure and head to the next challenge.",
        image: "./img/maze_game.jpg",
        link: "https://github.com/QI-D/Maze_Game",
        l1: "MVC Architecture",
        l2: "Time & Item Restriction",
        l3: "Score Counting",
        l4: "Test-Driven Development",
        l5: "Agile Methodology",
    }
]